// src/database.ts

export interface Anime {
  id: number;
  title: string;
  genre: string;
  episodes: string;
  imageUrl: string; // Novo campo para a URL da imagem
  sinopse: string;
}

export const animes: Anime[] = [
  { id: 1, title: 'Atack on Titan', genre: 'Ação/Fantasia', episodes: '4 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/10/47347.jpg', sinopse: 'Ambientado num mundo onde a humanidade vive protegida por enormes muralhas para se defender dos Titãs, criaturas gigantescas que devoram humanos. A história segue Eren Jaeger, que, após testemunhar a morte da sua mãe e a destruição da sua cidade, junta-se à Tropa de Exploração para lutar contra os Titãs e descobrir a verdade sobre a sua origem. '},
  { id: 2, title: 'One Piece', genre: 'Aventura/Shonen', episodes: '1100 Episodios', imageUrl: 'https://cdn.myanimelist.net/images/anime/6/73245.jpg', sinopse: 'One Piece conta a história de Monkey D. Luffy e sua tripulação, os Piratas do Chapéu de Palha, que navegam pelos mares em busca do lendário tesouro "One Piece", deixado para trás pelo Rei dos Piratas Gold D. Roger, para que Luffy possa se tornar o próximo Rei dos Piratas.'},
  { id: 3, title: 'Naruto', genre: 'Aventura/Shonen', episodes: '220 Episodios', imageUrl: 'https://cdn.myanimelist.net/images/anime/13/17405.jpg', sinopse: 'Conta a história de Naruto Uzumaki, um jovem órfão que foi rejeitado pela aldeia por ter um demônio raposa de nove caudas selado dentro de si, e que sonha em se tornar o líder ninja da sua vila, o Hokage. No mundo de Naruto, ninjas usam chakra para realizar jutsus, criando habilidades sobre-humanas, e a série acompanha a jornada de Naruto para ganhar reconhecimento e proteger seus amigos. '},
  { id: 4, title: 'DandaDan', genre: 'Comedia/Ação/Ficção Cientifica', episodes: '2 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1584/143719.jpg', sinopse: 'Conta a história de Momo Ayase, uma menina que acredita em fantasmas, e Ken Takakura, conhecido como Okarun, um garoto obcecado por alienígenas. Após desafiarem um ao outro para provar suas crenças, eles se deparam com uma realidade cheia de criaturas sobrenaturais e acabam ganhando poderes ocultos, embarcando numa aventura épica que envolve demônios, alienígenas e a possibilidade de uma história de amor. '},
  { id: 5, title: 'Kaiju n 8', genre: 'Shonen', episodes: '2 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1370/140362.jpg', sinopse: 'Kafka Hibino, que trabalha na limpeza de restos de monstros (kaijus) mas sonha em se juntar à Força de Defesa para combater essas criaturas ameaçadoras. Após ser infectado por um parasita, Kafka ganha a habilidade de se transformar no poderoso "Kaiju No. 8" e, ao mesmo tempo que tenta se misturar à Força de Defesa para cumprir uma promessa de infância, precisa esconder sua identidade monstruosa.'},
  { id: 6, title: 'Hunter x Hunter', genre: 'Aventura/Shonen', episodes: '6 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1337/99013.jpg', sinopse: 'Segue Gon Freecss, um garoto de 12 anos que descobre que seu pai, Ging, está vivo e é um lendário Hunter, um profissional que busca tesouros e perigos por um mundo repleto de criaturas e locais misteriosos. Gon decide se tornar um Hunter para encontrar o pai, passando por um rigoroso exame e fazendo amigos como Killua, Kurapika e Leorio. '},
  { id: 7, title: 'Jujutsu Kaisen', genre: 'Aventura/Shonen', episodes: '2 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1171/109222.jpg', sinopse: 'Conta a história de Yuji Itadori, um adolescente que se torna o hospedeiro do poderoso espírito amaldiçoado Ryomen Sukuna após engolir um de seus dedos para proteger amigos. Para controlar a maldição e salvar a humanidade, Yuji entra para o Colégio de Jujutsu de Tóquio, uma organização secreta de feiticeiros, e passa a combater criaturas malignas conhecidas como Maldições, usando a energia amaldiçoada para lutar contra elas. '},
  { id: 8, title: 'Nanatsu no Taisai', genre: 'Aventura/Shonen', episodes: '5 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/8/65409.jpg', sinopse: 'A princesa Elizabeth busca os Sete Pecados Capitais, um grupo de cavaleiros lendários, para resgatar seu reino. Dez anos antes, os Sete Pecados Capitais foram acusados de conspirar contra a família real, mas foram considerados desaparecidos e substituídos pelos cavaleiros tiranos que agora governam o reino, forçando Elizabeth a reunir os Pecados e restaurar a ordem em Britânia. '},
  { id: 9, title: 'Demon Slyer', genre: 'Aventura/Shonen', episodes: '4 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1565/142711.jpg', sinopse: 'Segue Tanjiro Kamado, um jovem bondoso cuja família é massacrada por demónios, com exceção da sua irmã mais nova, Nezuko, que é transformada em um demónio. Tanjiro junta-se ao Corpo de Caçadores de Demónios para vingar a sua família e encontrar uma forma de curar Nezuko, lutando contra demónios ao lado dos seus companheiros. A série foca-se na jornada de Tanjiro, os seus treinos e batalhas, e a luta contra o Rei dos Demónios, Muzan Kibutsuji. '},
  { id: 10, title: 'Dragon Ball Z', genre: 'Aventura/Shonen', episodes: '291 Episodios', imageUrl: 'https://cdn.myanimelist.net/images/anime/1833/93679.jpg', sinopse: 'Dragon Ball Z é a continuação de Dragon Ball, focada na vida adulta de Son Goku e seus companheiros, que defendem a Terra de uma variedade de vilões intergalácticos, como conquistadores espaciais e criaturas poderosas. A série aborda a ameaça de alienígenas, androides e seres mágicos, enquanto acompanhamos o amadurecimento do filho de Goku, Gohan, e o desenvolvimento da rivalidade entre Goku e Vegeta, de inimigos a aliados. '},
  { id: 11, title: 'My Hero Academy', genre: 'Aventura/Shonen', episodes: '8 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/10/78745.jpg', sinopse: 'É a história de Izuku Midoriya, um garoto sem poderes (ditos "Individualidades") num mundo onde a maioria das pessoas as tem. Fã de heróis, especialmente do poderoso All Might, Izuku sonha em se tornar um. Após um encontro crucial, All Might transfere sua Individualidade para Izuku, permitindo que ele entre na Academia U.A., a principal escola de super-heróis. A série acompanha sua jornada para desenvolver o poder e se tornar o maior herói que ele sempre quis ser, enfrentando vilões e desafios enquanto aprende a ser um herói profissional. '},
  { id: 12, title: 'Haikyuu', genre: 'Aventura/Shonen', episodes: '4 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1453/106768.jpg', sinopse: 'Segue Shoyo Hinata, um baixinho apaixonado por vôlei que, após ver seu ídolo "Pequeno Gigante", decide seguir seus passos e se tornar um grande jogador. Ele se junta ao time de vôlei do Colégio Karasuno, onde tem uma surpresa: seu rival do ensino fundamental, Tobio Kageyama, também está lá. Juntos, Hinata e Kageyama, o prodígio do vôlei, precisam superar suas diferenças e a rivalidade para erguer o time do Karasuno e se tornarem campeões, focando na união e no trabalho em equipe. '},
  { id: 13, title: 'Mob Psycho 100', genre: 'Aventura/Shonen', episodes: '3 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/8/80356.jpg', sinopse: 'Segue Shigeo Kageyama, ou "Mob", um estudante do ensino médio com poderosos poderes psíquicos que ele tenta suprimir para viver uma vida normal e inexpressivo, temendo que suas emoções reprimidas causem um incidente catastrófico quando atingirem 100% de intensidade. Para controlar suas habilidades, ele trabalha como assistente para Reigen Arataka, um charlatão que finge ser um vidente. A vida de Mob se complica quando ele e Reigen se envolvem com uma organização secreta de espers com intenções sinistras. ' },
  { id: 14, title: 'Solo Leving', genre: 'Aventura/Shonen', episodes: '2 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1801/142390.jpg', sinopse: 'Segue Sung Jinwoo, o caçador mais fraco do mundo, que, após ser gravemente ferido numa masmorra, descobre um sistema misterioso que lhe permite subir de nível e ganhar força ilimitadamente. Num mundo onde humanos com habilidades mágicas lutam contra monstros de portais interdimensionais, Jinwoo passa de um E-rank impotente a um poder crescente, descobrindo um segredo que pode transformar a guerra entre as dimensões e a própria raça humana. '},
  { id: 15, title: 'SpyxFamily', genre: 'Aventura/Shonen', episodes: '2 Temporadas', imageUrl: 'https://cdn.myanimelist.net/images/anime/1441/122795.jpg', sinopse: 'Em Spy x Family, o espião Twilight precisa formar uma família falsa para completar a "Operação Strix", que tem como objetivo manter a paz entre as nações de Westalis e Ostania. Ele adota Anya, uma telepata que não é revelada aos pais, e se casa com Yor, uma assassina que esconde seu trabalho para ele. Juntos, essa família improvável busca manter as aparências enquanto cada um guarda seus segredos. '},
];